version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: "always"

  # Database explorer
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    env_file:
      - ./config/pgadmin.env
    ports:
      - 15432:80
    volumes:
      - pgadmin_volume:/pgadmin/pgadmin:/var/lib/pgadmin
      - ./pgadmin/docker_pgadmin_servers.json:/pgadmin4/servers.json

    restart: "always"

    depends_on:
      - postgres

  fastapi:
    build: ./fastapi
    environment:
      - APP_MODULE=app:app
    depends_on:
      - postgres
    ports:
      - "8000:80"
    command: bash -c "sleep 30 && uvicorn app:app --host=0.0.0.0 --port=80"
    volumes:
      - ./fastapi:/app
    restart: "always"

volumes:
  postgres-data:
  pgadmin_volume:
  data:


networks:
  network:
    driver: bridge
