version: '3.9'

services:

  fastapi:
    build: ./fastapi
    environment:
      - APP_MODULE=app:app
    ports:
      - "8000:80"
    command: bash -c "sleep 30 && uvicorn app:app --host=0.0.0.0 --port=80"
    volumes:
      - ./fastapi:/app
    restart: "always"

volumes:
  data:


networks:
  network:
    driver: bridge
