"""Punto de Control 2

Revision ID: 4b34192ce629
Revises: 8cc2ebc5ab87
Create Date: 2023-06-14 09:51:01.950937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b34192ce629'
down_revision = '8cc2ebc5ab87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('wisphub_update', sa.Boolean(), nullable=True))
    op.alter_column('clientes_wisphub', 'id_servicio',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_clientes_wisphub_id_servicio', table_name='clientes_wisphub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clientes_wisphub_id_servicio', 'clientes_wisphub', ['id_servicio'], unique=False)
    op.alter_column('clientes_wisphub', 'id_servicio',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('clientes', 'wisphub_update')
    # ### end Alembic commands ###
