"""Agregando tabla clientes_wisphub

Revision ID: 8cc2ebc5ab87
Revises: 6b7f104859f6
Create Date: 2023-06-07 19:39:01.817502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc2ebc5ab87'
down_revision = '6b7f104859f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_wisphub',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.Text(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('cedula', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('localidad', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('descuento', sa.Text(), nullable=True),
    sa.Column('saldo', sa.Text(), nullable=True),
    sa.Column('rfc', sa.Text(), nullable=True),
    sa.Column('informacion_adicional', sa.Text(), nullable=True),
    sa.Column('notificacion_sms', sa.Boolean(), nullable=True),
    sa.Column('aviso_pantalla', sa.Boolean(), nullable=True),
    sa.Column('notificaciones_push', sa.Boolean(), nullable=True),
    sa.Column('auto_activar_servicio', sa.Boolean(), nullable=True),
    sa.Column('firewall', sa.Boolean(), nullable=True),
    sa.Column('servicio', sa.Text(), nullable=True),
    sa.Column('password_servicio', sa.Text(), nullable=True),
    sa.Column('server_hotspot', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('ip_local', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('modelo_antena', sa.Text(), nullable=True),
    sa.Column('password_cpe', sa.Text(), nullable=True),
    sa.Column('mac_cpe', sa.Text(), nullable=True),
    sa.Column('interfaz_lan', sa.Text(), nullable=True),
    sa.Column('modelo_router_wifi', sa.Text(), nullable=True),
    sa.Column('ip_router_wifi', sa.Text(), nullable=True),
    sa.Column('mac_router_wifi', sa.Text(), nullable=True),
    sa.Column('usuario_router_wifi', sa.Text(), nullable=True),
    sa.Column('password_router_wifi', sa.Text(), nullable=True),
    sa.Column('ssid_router_wifi', sa.Text(), nullable=True),
    sa.Column('password_ssid_router_wifi', sa.Text(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('coordenadas', sa.Text(), nullable=True),
    sa.Column('costo_instalacion', sa.Text(), nullable=True),
    sa.Column('precio_plan', sa.Text(), nullable=True),
    sa.Column('forma_contratacion', sa.Text(), nullable=True),
    sa.Column('sn_onu', sa.Text(), nullable=True),
    sa.Column('estado_facturas', sa.Text(), nullable=True),
    sa.Column('fecha_instalacion', sa.Text(), nullable=True),
    sa.Column('fecha_cancelacion', sa.Text(), nullable=True),
    sa.Column('fecha_corte', sa.Text(), nullable=True),
    sa.Column('ultimo_cambio', sa.Text(), nullable=True),
    sa.Column('sectorial', sa.Text(), nullable=True),
    sa.Column('plan_internet_id', sa.Integer(), nullable=True),
    sa.Column('plan_internet_nombre', sa.Text(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('zona_nombre', sa.Text(), nullable=True),
    sa.Column('router_id', sa.Integer(), nullable=True),
    sa.Column('router_nombre', sa.Text(), nullable=True),
    sa.Column('tecnico_id', sa.Float(), nullable=True),
    sa.Column('tecnico_nombre', sa.Text(), nullable=True),
    sa.Column('tecnico', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_internet_id'),
    sa.UniqueConstraint('router_id'),
    sa.UniqueConstraint('zona_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes_wisphub')
    # ### end Alembic commands ###
