"""Agregando nueva estructura de datos geografico

Revision ID: c3288d96e028
Revises: c439970e0911
Create Date: 2023-06-07 13:56:16.422665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3288d96e028'
down_revision = 'c439970e0911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comunidades', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('comunidades', sa.Column('parroquias_id', sa.Integer(), nullable=True))
    op.drop_constraint('comunidades_id_parroquia_fkey', 'comunidades', type_='foreignkey')
    op.create_foreign_key(None, 'comunidades', 'parroquias', ['parroquias_id'], ['id'])
    op.drop_column('comunidades', 'desc_cominidad')
    op.drop_column('comunidades', 'id_parroquia')
    op.add_column('estados', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('estados', sa.Column('pais_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estados', 'pais', ['pais_id'], ['id'])
    op.drop_column('estados', 'estado')
    op.drop_column('estados', 'desc_estado')
    op.add_column('municipios', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('municipios', sa.Column('estados_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_municipios_estados_1', 'municipios', type_='foreignkey')
    op.create_foreign_key(None, 'municipios', 'estados', ['estados_id'], ['id'])
    op.drop_column('municipios', 'desc_municipio')
    op.drop_column('municipios', 'cod_municipio')
    op.drop_column('municipios', 'id_estado')
    op.add_column('parroquias', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('parroquias', sa.Column('municipios_id', sa.Integer(), nullable=True))
    op.drop_constraint('parroquias_id_municipio_fkey', 'parroquias', type_='foreignkey')
    op.create_foreign_key(None, 'parroquias', 'municipios', ['municipios_id'], ['id'])
    op.drop_column('parroquias', 'id_estado')
    op.drop_column('parroquias', 'desc_parroquia')
    op.drop_column('parroquias', 'id_municipio')
    op.drop_column('parroquias', 'siglas')
    op.drop_column('parroquias', 'cod_parroquia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parroquias', sa.Column('cod_parroquia', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parroquias', sa.Column('siglas', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('parroquias', sa.Column('id_municipio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parroquias', sa.Column('desc_parroquia', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('parroquias', sa.Column('id_estado', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parroquias', type_='foreignkey')
    op.create_foreign_key('parroquias_id_municipio_fkey', 'parroquias', 'municipios', ['id_municipio'], ['id'])
    op.drop_column('parroquias', 'municipios_id')
    op.drop_column('parroquias', 'name')
    op.add_column('municipios', sa.Column('id_estado', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('municipios', sa.Column('cod_municipio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('municipios', sa.Column('desc_municipio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'municipios', type_='foreignkey')
    op.create_foreign_key('fk_municipios_estados_1', 'municipios', 'estados', ['id_estado'], ['id'])
    op.drop_column('municipios', 'estados_id')
    op.drop_column('municipios', 'name')
    op.add_column('estados', sa.Column('desc_estado', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('estados', sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'estados', type_='foreignkey')
    op.drop_column('estados', 'pais_id')
    op.drop_column('estados', 'name')
    op.add_column('comunidades', sa.Column('id_parroquia', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comunidades', sa.Column('desc_cominidad', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comunidades', type_='foreignkey')
    op.create_foreign_key('comunidades_id_parroquia_fkey', 'comunidades', 'parroquias', ['id_parroquia'], ['id'])
    op.drop_column('comunidades', 'parroquias_id')
    op.drop_column('comunidades', 'name')
    op.drop_table('pais')
    # ### end Alembic commands ###
