"""agregando campo fue_migrado a la tabla clientes

Revision ID: c439970e0911
Revises: 53ca25326202
Create Date: 2023-06-04 18:39:53.515572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c439970e0911'
down_revision = '53ca25326202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('fue_migrado', sa.Boolean(), nullable=True))
    op.drop_constraint('fk_parroquias_estados_1', 'parroquias', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_parroquias_estados_1', 'parroquias', 'estados', ['id_estado'], ['id'])
    op.drop_column('clientes', 'fue_migrado')
    # ### end Alembic commands ###
